name: Terraform Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # ------------------------------
      # Authenticate to Azure
      # ------------------------------
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      # ------------------------------
      # Delete old diagnostic settings (to avoid conflicts)
      # ------------------------------
      - name: Delete old diagnostic settings
        run: |
          echo "Deleting old diagnostic settings if they exist..."
          az monitor diagnostic-settings delete --name diag-storage \
            --resource "/subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/rg-aravind-datavault/providers/Microsoft.Storage/storageAccounts/stgaravinddatavault" || true

          az monitor diagnostic-settings delete --name diag-kv \
            --resource "/subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/rg-aravind-datavault/providers/Microsoft.KeyVault/vaults/kv-aravind-datavault" || true

      # ------------------------------
      # Setup Terraform
      # ------------------------------
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      # ------------------------------
      # Terraform Init
      # ------------------------------
      - name: Terraform Init
        run: terraform init -input=false

      # ------------------------------
      # Terraform Plan
      # ------------------------------
      - name: Terraform Plan
        run: terraform plan -input=false

      # ------------------------------
      # Terraform Apply
      # ------------------------------
      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
